name: Publish to Github Registry on Tag

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Build with Gradle
        run: ./gradlew build -Pversion=${{ steps.get_version.outputs.VERSION }} -x test

      - name: Publish to Github registry
        env:
          GH_USER: ${{ secrets.GH_USER }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew publish
